---
- name: Configure system
  hosts: zabbix
  become: yes
  gather_facts: false
  vars: 
    zabbix_ports:
      - 10050/tcp
      - 10051/tcp
  tasks:
    - name: "open zabbix ports"
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ zabbix_ports }}"
      tags: open-ports
