---
- name: Configure system
  hosts: zabbix
  become: yes
  gather_facts: false
  tasks:
    - name: "open zabbix port"
      firewalld:
        port: "{{ zabbix_port }}"
        permanent: yes
        state: enabled
        immediate: yes
      tags: open-ports
   